import json

hints = {
    1: "Pense no processo de clonagem natural do corpo. É quando uma célula-mãe se divide criando duas filhas idênticas para consertar ferimentos.",
    2: "Sabe como uma esponja absorve a água? Esses seres jogam sucos digestivos fora do corpo e depois sugam a sopa pronta.",
    3: "Imagine uma pequena fábrica verde dentro da folha que usa a luz do sol para cozinhar o alimento da planta.",
    4: "Pense nessa estrutura como a 'usina de energia' da célula. É lá que o oxigênio e a comida se transformam em pura bateria (ATP).",
    5: "Imagine uma minúscula impressora 3D celular. Ela lê o manual (RNA) e fabrica todas as proteínas necessárias para a vida.",
    6: "É o famoso pergaminho em espiral da vida. Ele guarda o código genético de todas as criaturas em formato de dupla-hélice.",
    7: "É a matemática mais simples da natureza: um ser vivo simplesmente se divide no meio, virando dois gêmeos idênticos.",
    8: "Imagine que o veneno não some, ele se acumula. Quem come muito, acaba guardando todo o veneno no corpo de uma vez.",
    9: "É o mesmo material que dá firmeza à madeira e ao papel. Nas plantas, ela age como um escudo duro ao redor das células.",
    10: "Eles funcionam como um cobertor térmico e um estoque de energia para o inverno. Muito presentes em óleos e gorduras.",
    11: "Pense nisso como colocar ou tirar etiquetas do DNA sem mudar as letras dele. O manual continua igual, mas algumas páginas ficam coladas.",
    12: "Eles são como a ponta de plástico do cadarço do tênis. Protegem as pontas dos cromossomos para não desfiarem a cada divisão.",
    13: "Se o ferro deixa o nosso sangue vermelho, esse outro metal deixa o sangue azul. O cobre é o segredo aqui.",
    14: "Assim como os primeiros colonos em uma terra vazia, eles chegam antes de todo mundo para preparar o solo das pedras nuas.",
    15: "Funciona como um radar natural. O animal grita e ouve o eco bater na parede para enxergar no escuro.",
    16: "Pense no fio do carregador do seu celular. Essa bainha é a capa de borracha que isola a energia e faz o choque viajar mais rápido.",
    17: "Imagine uma fábrica celular sem as 'bolinhas' (ribossomos) grudadas. O foco dela é quebrar toxinas e remédios.",
    18: "Lembra da velha tabela do jogo da velha (quadrado de Punnett)? Quando misturamos dois híbridos (Aa), a minoria é a fraca (aa).",
    19: "É como quando você toma um susto e se encolhe na mesma hora. A planta reage a um impacto mecânico fechando-se.",
    20: "Se a vacina ensina o corpo a lutar, esse método é como já mandar os soldados armados (anticorpos) de fora para dentro.",
    21: "É literalmente o 'suicídio' da célula. Ela rompe suas bolsas de ácido interno para derreter a si mesma.",
    22: "Ela é formada por um sanduíche de gorduras (lipídios) e fósforo, com algumas proteínas flutuando no meio.",
    23: "Eles têm o corpo liso e comprido feito um fio de macarrão cilíndrico, diferentemente da minhoca que tem anéis.",
    24: "É o gás que respiramos o tempo todo. Ele fica no fim da linha de montagem celular para receber a sujeira final (elétrons) e virar água.",
    25: "É o tecido durinho mas flexível que forma a ponta do nosso nariz e as orelhas. É a proteção das juntas dos ossos.",
    26: "Pense neles como as 'boquinhas' ou poros das folhas. Eles se abrem para a planta respirar e suar água.",
    27: "O universo busca o equilíbrio! Para matar o extremo Ácido (abaixo de 7), você joga o extremo oposto (acima de 7).",
    28: "É como ver um cubo de gelo virando água do lado de fora do congelador. O duro vira líquido.",
    29: "Eles ficam na primeira coluna da tabela, são parceiros da água na violência e formam substâncias básicas.",
    30: "Quando você mistura perfeitamente sal e água, não dá mais para ver o sal. A ciência chama essa perfeição de outro nome.",
    31: "Qualquer coisa que queima e solta fogo está fazendo isso. É a reação química de 'queimar'.",
    32: "Pense num ácido clássico como alguém que sempre solta um 'H+' na água para deixá-la azeda.",
    33: "Imagine um mar de elétrons livres nadando entre átomos felizes. É assim que os metais se abraçam.",
    34: "Essa lei explica por que o monóxido e o dióxido existem. Os elementos se combinam sempre em números inteiros fáceis.",
    35: "Eles são a 'realeza' da tabela. Não se misturam com a plebe porque já são perfeitos sozinhos (completos).",
    36: "Quando os átomos precisam compartilhar os elétrons, mas um puxa mais forte que o outro, criando polos positivo e negativo.",
    37: "É o pulo mágico sem passar pela água! O vapor vira gelo duro instantaneamente.",
    38: "O nome desse processo lembra algo que ficou 'menor'. O material recebe carga negativa e seu número de oxidação diminui.",
    39: "Olhe para a equação matemática do guerreiro: o número grandão que fica à esquerda do 'O2' é a resposta que procura.",
    40: "É o mesmo princípio usado para fazer um bom café passado. Uma barreira física retém o sólido e passa o líquido.",
    41: "Imagine ferver a mistura. O líquido mais 'fácil' vira gás primeiro, sobe pelo cano e depois vira líquido de novo em outro pote.",
    42: "O Cálcio tem 2 elétrons sobrando para dar (Ca+2). Cada Cloro só consegue pegar 1. Você precisará de mais de um Cloro para fechar a conta.",
    43: "Ferrugem não existe no vácuo! Ela precisa do gás invisível que nós respiramos para atacar o metal.",
    44: "É como encontrar um atalho no mapa da masmorra. Ele não gasta sola de sapato (não é consumido) e deixa tudo mais rápido.",
    45: "O mundo do meio é o 7 (Neutro). O ácido mora abaixo do 7, e o alcalino (básico) mora do outro lado.",
    46: "Imagine um tripé de câmera fotográfica com mais uma perna apontando para o céu. São quatro pontas equidistantes.",
    47: "É a capacidade de um mesmo elemento usar 'roupas' diferentes. O Carbono pode vestir carvão ou vestir joia cara.",
    48: "Se o frasco gelou, é porque a reação roubou o calor da sua mão (e do ambiente) para acontecer. É como sugar o calor.",
    49: "Olhe para a fórmula do ácido (H₂SO₄). O número pequenininho logo depois do H diz quantos guerreiros ele libera na água.",
    50: "Como os dois lutadores (átomos de fósforo) têm a mesma força, ninguém puxa mais a corda. O empate é sem polos.",
    51: "A regra de ouro de neutralização simples: 1 guerreiro de H precisa exatamente de 1 guerreiro de OH para empatar a luta.",
    52: "O segredo está no último número daquela sequência de distribuição. O último anel do átomo de alumínio entrega a resposta.",
    53: "Fórmula rápida: Multiplique a velocidade pelo tempo de voo. Um atira reto a 10m/s e viaja por 2 segundos. Quanto longe ele vai?",
    54: "As luzes de Natal modernas funcionam assim. Se uma lâmpada queima, a energia encontra atalho e as outras não se importam.",
    55: "Quem ganha a batalha? O mago puxa 15 pra cima e o planeta puxa 10 pra baixo. A força vencedora empurra a massa de 1kg.",
    56: "É como jogar bilhar com a parede. O ângulo que a bolinha de luz bate na parede é idêntico ao ângulo que ela volta.",
    57: "É energia de suor! Multiplique a força que ele fez pelos metros que andou. (50 vezes 4).",
    58: "Se a temperatura não sobe nem desce, esse calor está focado apenas em mudar a forma da água. Fica 'escondido'.",
    59: "Se você entrar na banheira, a água transborda. A força mágica que empurra de volta é exatamente o peso da água que vazou.",
    60: "Lembra que a atração cai rápido com o quadrado da distância. Se distanciou 2 vezes, a força divide por 2² (que é 2x2).",
    61: "É o calor passando de mão em mão. O fogo esquenta a espada, que esquenta a placa, que esquenta o escudo (átomo a átomo).",
    62: "Pense num trem passando: você sente o barulho tremer no trilho de ferro antes mesmo de ouvir no ar.",
    63: "A velocidade diminui enquanto a altura aumenta. A energia do movimento está se guardando na energia da altitude.",
    64: "O prisma espalha a luz. Cada cor tem uma velocidade diferente ao atravessar o cristal mágico e acaba separada das irmãs.",
    65: "Naquela fórmula matemática, o número livre é de onde ele partiu, e o número colado na letra 't' é o quão rápido ele vai.",
    66: "A energia do universo não some, apenas muda de corpo. Se os dois bateram, a soma dos movimentos nunca se perde.",
    67: "Tem formato de colher. Pense no formato curvo para dentro que abraça a luz, focando tudo num ponto só.",
    68: "Divida o empurrão da bateria (12V) pela dificuldade do caminho (4 Ohms). Quanto passa? (12 dividido por 4).",
    69: "Divida o empurrão forte de 20N pelo peso da pedra de 2kg. Você verá quantos metros por segundo o bloco acelera.",
    70: "Veja o quanto ele acelerou: de 2 foi para 14, então cresceu 12. Demorou 3 segundos pra isso. (12 dividido por 3).",
    71: "Quanto mais longe do centro do feitiço, muito mais fraco ele fica. É por causa do 'quadrado da distância'.",
    72: "Quando você aperta um balão com água, a pressão se espalha inteira lá dentro. Leva o nome do cientista Blaise P.",
    73: "Os opostos se amam, os iguais se odeiam. Charles Augustin deu nome à lei que rege esse balé de cargas elétricas.",
    74: "Multiplique o nível de lixa do chão (0,3) pela força Normal (peso de 100N do baú).",
    75: "Mesmo se tirar todo o ar da sala, o fogo te esquenta. É o calor viajando por raios invisíveis, feito o Sol.",
    76: "É o puxão misterioso que não deixa a pedra voar reto. Ela sempre aponta para a sua mão (para o centro).",
    77: "É o truque do copo d'água: parece que o canudo está quebrado. A luz dobra quando muda de ar para a água mágica.",
    78: "Quando a energia elétrica precisa empurrar pelo metal apertado, ela esquenta tudo de tanto esfregar.",
    79: "Pense na água de uma panela de sopa evaporando pela tampa. É a passagem direta do líquido quente para o ar como vapor.",
    80: "O pó não some, ele só fica voando um pouco na água e logo cai pro fundo como uma tempestade de areia de brinquedo.",
    81: "Um metal valioso que não pode ser desmanchado em outros materiais. É o brilho mais puro dos reis antigos.",
    82: "A madeira nunca mais voltará a ser madeira depois do fogo, virou fumaça. As propriedades da matéria foram alteradas pra sempre.",
    83: "Se a escala é 7 no meio e o monstro tem pH 1, isso significa que ele está na ponta que derrete metais na hora.",
    84: "É a primeira letra da palavra que você respira! Esse elemento vital guarda o segredo.",
    85: "As moléculas de água dão as mãos tão forte na superfície que criam uma cama elástica invisível, como uma película.",
    86: "Se não se mistura, se você consegue enxergar a linha que separa o óleo da água, é porque não formou um todo perfeito.",
    87: "Ninguém roubou os elétrons, eles apenas deram as mãos. Eles dividem pacificamente o prêmio.",
    88: "Lembre-se da inicial da palavra. Uma partícula subatômica com carga *p*ositiva.",
    89: "Ele dizia que na natureza nada se perde e nada se cria, mas sim algo maravilhoso que começa com 'T'.",
    90: "As reações sempre acontecem pela parte mais externa do átomo, a última 'capa' de armadura antes do espaço vazio.",
    91: "A água secou pela metade, mas todo o sal que estava lá não saiu. A concentração de sal agora ficou muito mais forte! (O dobro).",
    92: "Eles ficam sozinhos na natureza por escolha! São os reis da estabilidade e estão na extrema direita da tabela.",
    93: "Pense no número que divide a régua mágica no meio certinho: metade pra ácido, metade pra alcalino.",
    94: "O poder do átomo de roubar elétrons dos outros lembra o lado vilão do magnetismo. Quem é mais negativo ganha a disputa.",
    95: "O calor sai e o pote fica muito quente! 'Exo' significa ir para fora. É energia fugindo para o ambiente.",
    96: "Em uma batalha de quem dá ou recebe carga, ele é aquele herói altruísta que perde sua energia doando-a para outro se salvar.",
    97: "É a velha receita de bolo! Se de 1 mol fazemos 2 produtos (o dobro), de 3 mols faremos quantas vezes o produto?",
    98: "O gás da putrefação pântano! Pense na molécula formada por um único átomo de carbono rodeado por quatro de hidrogênio.",
    99: "O equilíbrio sempre luta contra a mudança! Se você empurrar, ele faz de tudo para voltar ao estado de paz original.",
    100: "Representada com uma letra 'K' acompanhada de um 'c'. É a balança que decide para que lado a reação é mais forte.",
    101: "Pressão e volume funcionam como uma gangorra em gás de temperatura fixa. Se você apertar forte com o dobro de força, o espaço reduzirá à metade.",
    102: "Lembre-se que o Carbono forma duas retas retinhas (uma de cada lado). Uma hibridização retilínea clássica feita de s e p.",
    103: "Multiplique a rapidez pelos segundos que ele passou correndo e você achará quantos passos mágicos ele deu.",
    104: "É a mão invisível do planeta que impede você de flutuar. Ela depende da massa da terra.",
    105: "Se a velocidade aumenta, você pisa num pedal que os magos modernos dos carros chamam de... ?",
    106: "A massa é a matéria em si e nunca muda de quantidade! Não se confunda com peso, que depende da lua.",
    107: "Ela guarda o poder da queda livre. É o poder da 'altura' mágica esperando ser liberto sobre o alvo.",
    108: "Imagine um rio de centelhas de raio andando certinho num fio de cobre. É um 'rio' elétrico, uma corrente.",
    109: "A onda bate e volta para você como se olhasse para um espelho d'água sonoro.",
    110: "Tem o nome do cientista que levou uma maçã na cabeça para entender a gravidade.",
    111: "A 'preguiça' natural de todas as coisas. Tudo gosta de manter o mesmo estado pra sempre, se nada o empurrar.",
    112: "Sem caminho, não há jornada! Numa fila indiana (série), quebrar um pedaço desliga tudo.",
    113: "Ohm percebeu que Empurrão = Dificuldade * Rio de energia. Qual grandeza mede a passagem desse rio mágico (I)?",
    114: "A água quente vira vapor e sobe, a água fria e pesada desce. Esse movimento em espiral pelo ar tem nome de 'convectivo'.",
    115: "Entrar num rio freia seu corpo e muda sua trajetória. A luz sente a mesma 'quebra' ao trocar o meio transparente.",
    116: "Aceleração é Força dividida pela Massa! Quanto é o empurrão de 30 N num corpo de 5 kg? (30/5)",
    117: "Imagine duas cristas de uma onda do mar. A distância entre elas mede o tamanho total desse 'comprimento' da energia.",
    118: "O trabalho físico do mago é simples: basta multiplicar a força de 20 pelos metros andados. Não esqueça a conta (20x5).",
    119: "Eles batem e as engrenagens de ferro se prendem uma na outra feito ímã, não quicando de volta.",
    120: "A atração do centro, que puxa o patrulheiro para dentro da curva redonda sem deixá-lo escapar.",
    121: "O abraço de atração cai rápido. Ele diminui com base matemática que multiplica a distância por ela mesma.",
    122: "Aproximar ímãs mágicos perto da bobina de cobre sem tocá-la faz nascer uma voltagem de força induzida (f.e.m).",
    123: "Bernoulli observou a água em canos: quando a água corre mais rápido, a pressão cai, mantendo toda a energia intacta sem perda.",
    124: "Tem barriga pra fora, feito a parte de trás da colher. Ele espalha a luz e deixa sua imagem de pé, porém gordinha e menor.",
    125: "Velocidade = Comprimento * Frequência. Corte os zeros e veja qual número multiplicado dá 300.",
    126: "Na magia dos caminhos alternativos, cada um recebe o poder inteiro direto da fonte. Um apagar não rouba força dos irmãos.",
    127: "A 'Casa da Energia' das células. É ali dentro das membranas dobradas que o açúcar e oxigênio viram poder (ATP).",
    128: "A menor pecinha do lego vivo. Sem essa unidade, nenhum monstro de biologia existiria.",
    129: "Elas têm o luxo de possuir um 'bunker' para esconder o DNA, uma carioteca. São as mais complexas, diferindo das bactérias.",
    130: "É a sigla gringa para Ácido Desoxirribonucleico, o roteiro com espirais onde está desenhado todo o projeto de sua carne.",
    131: "Eles começam o banquete. Transformam luz do Sol em biscoitos mágicos e comida para o mundo todo.",
    132: "É o feitiço solar das folhas verdes. Usa a energia para cozinhar ar e água e transformá-los em doçura e sustento.",
    133: "A pequena 'máquina de costura' de carne que lê o papel do RNA e junta todos os aminoácidos da poção para criar músculos.",
    134: "O conjunto de estradas, rios vermelhos (veias e artérias) e o grande tambor que faz o coração bater no peito do guerreiro.",
    135: "A matemática mágica da reprodução: ela não duplica, ela divide por dois a herança para criar sementes reprodutivas (espermatozóides).",
    136: "O monge Gregor cultivava ervilhas rúnicas e descobriu que as características vêm em duplas que se dividem puras nas sementes filhas.",
    137: "A sobrevivência do mais astuto. Quem nasce com o bico mais torto para pescar sobrevive melhor e gera filhos de bico torto.",
    138: "Uma bolsa minúscula cheia de ácido corrosivo dentro de você para engolir sujeiras, invasores ou comer lixo celular.",
    139: "O nome desse processo nas cristas da mitocôndria inclui elétrons escorregando e oxigênio queimando fósforo.",
    140: "Eles se dividem exatamente ao meio. É a cópia exata do original, bipartindo-se em duas porções solitárias.",
    141: "O feixe de energia que usa fios chamados de neurônios para sentir fogo ou correr. Pense em quem controla a sua mente.",
    142: "Elas aceleram tudo sem que você exploda de calor. São 'trabalhadoras' biológicas feitas de blocos construtores que não acabam.",
    143: "As capas de cima dos genes. Você não reescreve a palavra mágica, você apenas pinta por cima se quiser silenciar ou acordar a leitura do DNA.",
    144: "É a enzima 'zipper' biológica. Ela desliza pela molécula do DNA e abre a escada desfazendo as amarras de hidrogênio (cortando a hélice).",
    145: "Eles encaixam perfeitamente as 3 letras como se fossem chave e fechadura: o transportador tem 'anti' e o leitor tem as 3 iniciais.",
    146: "O tubarão caça muitos peixes pequenos envenenados, acumulando nele toda a sujeira. Pense naqueles que comem todos embaixo.",
    147: "É o treinamento para a guerra celular. Seu sistema viu a doença fraca (vacina), ativou o modo luta e agora o exército tem armas prontas e memorizadas.",
    148: "Sem eles, o DNA do guerreiro viraria um novelo de lã emaranhado! Eles são os carretéis que enrolam e compactam as fitas gigantes em pacotinhos cromossomos.",
    149: "É feito com bastante cálcio para ser forte o suficiente para formar um esqueleto que aguente o pulo e não se quebre.",
    150: "Acontece na fase em que a célula se prepara para se multiplicar dobrando suas espirais. Ela 'sintetiza' o dobro de código, a famosa fase cujo nome inicia com Síntese."
}

with open('data/questions.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for q in data:
    qid = q.get('id')
    if qid in hints:
        q['dica'] = hints[qid]

with open('data/questions.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
